[build]
builder = "nixpacks"

[variables]
DOTNET_SDK_VERSION = "8.0.100"


[phases.build]
cmds = ["dotnet restore", "dotnet build"]

[phases.start]
cmds = ["dotnet run --project Petabit/Petabit.csproj"]
