services:
  - type: web
    name: petabit
    env: docker
    region: frankfurt
    branch: master
    dockerfilePath: Dockerfile
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/Petabit.dll"
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}
